# Generated by Django 5.0.2 on 2024-03-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_food'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='food',
            table='foods',
        ),
    ]
